 <?php // List mode ?>
    <?php if($layout_mode!='grid'): ?>
        <div class="_item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>" itemtype="http://schema.org/Product" itemscope>
                <div class="product-content">
				<div class="row">
					<?php // Product Image ?>
                    <?php $productId = $_product->getId();  ?>
					<div class="col-lg-4 col-sm-4 col-xs-12">
                        <?php
                            $swap_class = "";
                            if($swap_image && $hover_image = $helper->getProductImage($_product->getId(), 0, $list_image_width, $list_image_height)) {
                                    $swap_class = "swap";
                             } 
                        ?>
						<div class="image <?php echo $swap_class; ?>">
							<a itemprop="url" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($list_image_width, $list_image_height); ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                             <?php if($swap_class) { ?>
                                <span class="hover-image">
                                    <a itemprop="url" class="img" href="<?php echo $_product->getProductUrl(); ?>"><img src="<?php echo $hover_image; ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"></a>
                                </span>
                                <?php } ?>
                        </div>
                         <?php if ($quickview) { ?>
                            <a class="ves-colorbox" href="<?php echo Mage::helper("ves_tempcp")->getQuickviewURL( $_product->getProductUrl() ); ?>" title="Quick View"><span class='fa fa-eye'></span><?php echo $this->__('Quick View'); ?></a>
                        <?php } ?>
                        <?php if( $categoryPzoom ) { ?>
                        <?php
                            
                            $_product2 = Mage::getModel('catalog/product')->load($productId);
                        ?>

                        <a href="<?php echo $this->helper('catalog/image')->init($_product2, 'image')->resize($popup_image_width, $popup_image_height);?>" class="colorbox product-zoom" rel="colorbox" title="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>"><span class="icon-zoom-in"></span></a>
                        <?php } ?>
                    </div>
                    <?php // Product description ?>
                    <div class="col-lg-8 col-sm-8 col-xs-12">
                        <div class="product-meta product-shop">
                            <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                            <h2 class="product-name" itemprop="name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                            <?php if($show_review): ?>
                            <div class="rating">
                                <?php echo $this->getReviewsSummaryHtml($_product) ?>
                            </div>
                            <?php endif; ?>
                            <div class="price">
								<?php 
								    /* echo $this->getPriceHtml($_product, true) */
								    /* Sashas_Callfor_Price */
								          echo $this->getLayout()->createBlock('callforprice/listprice')->setProduct($_product)->setPrefix('')->toHtml();
								    /* Sashas_Callfor_Price */
								?>
                            </div>
                            <div class="desc">
                                <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                            </div>
                            <div class="add-to-box">
                                <?php if($_product->isSaleable()): ?>
                                <div class="add-to-cart">
					<?php 
					    /* Sashas_Callfor_Price */
					        echo $this->getLayout()->createBlock('callforprice/listcart')->setProduct($_product)->setAddUrl($this->getAddToCartUrl($_product))->setCustom(1)->toHtml();
					    /* Sashas_Callfor_Price */
					?>                                 
                                <!-- <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="<?php if($ajax_cart) { ?>addToCart('<?php echo $this->getAddToCartUrl($_product) ?>')<?php } else { ?>setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')<?php } ?>"><span><i class="fa fa-shopping-cart"></i><?php echo $this->__('Add to Cart') ?></span></button> -->
                                <?php else: ?>
                                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                <?php endif; ?>
                                <div class="add-to-links">
                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <div class="wishlist">
                                        <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="Toevoegen aan wenslijst" class="link-wishlist"><i class="fa fa-heart"></i></a>
                                    </div>
                                <?php endif; ?>
                                <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <div class="compare">
                                    <a href="<?php echo $_compareUrl ?>" title="Toevoegen aan vergelijken" class="link-compare"><i class="fa fa-refresh"></i></a>
                                </div>
                                <?php endif; ?>
                                </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php else: ?>

    <?php // Grid Mode ?>
            <?php $productId = $_product->getId(); ?>
            <div class="col-xs-12 col-lg-<?php echo $span;?> col-sm-<?php echo $small;?> col-<?php echo $mini;?> _item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <div class="product-block" itemtype="http://schema.org/Product" itemscope>
                    <div class="product-content">
                    <?php
                            $swap_class = "";
                            if($swap_image && $hover_image = $helper->getProductImage($_product->getId(), $swap_image_number, $list_image_width, $list_image_height)) {
                                    $swap_class = "swap";
                             } 
                        ?>
                    <div class="image <?php echo $swap_class; ?>">
                        <a href="<?php echo $_product->getProductUrl() ?>" itemprop="url" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($list_image_width, $list_image_height); ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                        <?php if($swap_class) { ?>
                                <span class="hover-image">
                                    <a class="img" itemprop="url" href="<?php echo $_product->getProductUrl(); ?>"><img src="<?php echo $hover_image; ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"></a>
                                </span>
                                <?php } ?>
                        <?php if ($quickview) { ?>
                            <a class="ves-colorbox" href="<?php echo Mage::helper("ves_tempcp")->getQuickviewURL( $_product->getProductUrl() ); ?>" title="Quick View"><span class='fa fa-eye'></span><?php echo $this->__('Quick View'); ?></a>
                        <?php } ?>
                        <?php if( $categoryPzoom ) { ?>
                        <?php
                            
                            $_product2 = Mage::getModel('catalog/product')->load($productId);
                        ?>

                        <a href="<?php echo $this->helper('catalog/image')->init($_product2, 'image')->resize($popup_image_width, $popup_image_height);?>" class="colorbox product-zoom" rel="colorbox" title="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>"><span class="icon-zoom-in"></span></a>
                        <?php } ?>

                    </div>
                <div class="product-info">
                    <h2 class="product-name" itemprop="name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
                    </h2>
                    <?php if($show_review ): ?>
                            <div class="rating"><?php echo $this->getReviewsSummaryHtml($_product, 'short') ?></div>
                        <?php endif; ?>
                    <?php if($enable_short_desc) { ?>
                            <div class="desc std" itemprop="desc">
                                <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                            </div>
                    <?php } ?>
                    
								<?php 
								    /* echo $this->getPriceHtml($_product, true) */
								    /* Sashas_Callfor_Price */
							  if(!Mage::registry('current_product'))
									          echo $this->getLayout()->createBlock('callforprice/listprice')->setProduct($_product)->setPrefix('')->toHtml();
								else 
									echo $this->getPriceHtml($_product, true);
								    /* Sashas_Callfor_Price */
								?>
                </div>
                <div class="add-to-links">
                        <div class="cart">
					<?php 
					    /* Sashas_Callfor_Price */
					if(!Mage::registry('current_product')):
					        echo $this->getLayout()->createBlock('callforprice/listcart')->setProduct($_product)->setAddUrl($this->getAddToCartUrl($_product))->setCustom(1)->toHtml();
					    /* Sashas_Callfor_Price */
					else:
					?>                          
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="<?php if($ajax_cart) { ?>addToCart('<?php echo $this->getAddToCartUrl($_product) ?>')<?php } else { ?>setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')<?php } ?>"><i class="fa fa-shopping-cart"></i></button> 
                     <?php endif;?>
                        </div>
                        <div class="button-group">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        
                                <div class="wishlist">
                                    <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="Add to wishlist" class="link-wishlist"><i class="fa fa-heart"></i></a>
                                </div>
                            <?php endif; ?>
                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <div class="compare">
                                    <a href="<?php echo $_compareUrl ?>" title="Toevoegen aan vergelijken" class="link-compare"><i class="fa fa-refresh"></i></a>
                                </div>
                        <?php endif; ?>
                        </div>
                </div>
            </div>
            </div>
    </div>
    <?php endif; ?>