<?php 
/**
 * @author		Sashas
 * @category    Sashas
 * @package     Sashas_Callforprice
 * @copyright   Copyright (c) 2013 Sashas IT Support Inc. (http://www.sashas.org)
 * @license     http://opensource.org/licenses/GPL-3.0  GNU General Public License, version 3 (GPL-3.0)

 */

$_product=$this->getProduct();
if (empty($_product))
 	$_product= Mage::registry('current_product');

$customer_group=$this->GetGroupId();
$show_cart=0;
$model=Mage::getModel('callforprice/callforprice')->loadByProductId($_product->getId());
 
if ($model->getId() && $model->getAddtocartEnabled()==1) {
	$show_cart=1;	
}
if (!$model->getId() || !$model->getStatus()) {
	$show_cart=1;
}
if (in_array($customer_group, explode(',',$model->getCustomerGroups()))) {
	$show_cart=1;
}
 
if ($show_cart){	 
  $buttonTitle = $this->__('Add to Cart');  
	  if($_product->isSaleable()): ?>
    <div class="add-to-cart">

            <?php if(!$_product->isGrouped()): ?>
            <div class="qty">
                <label for="qty"><?php echo $this->__('Qty:') ?></label>
                <input id="qty" class="input-text qty" type="text" title="Qty" value="<?php echo $this->getProductDefaultQty() * 1 ?>" maxlength="12" name="qty" />
            </div>
            <?php endif; ?>
            <button class="button btn-cart" title="<?php echo $buttonTitle ?>" type="button" onClick="productAddToCartForm.submit(this)"><i class="icon-basket"></i><?php echo $buttonTitle ?></button>


    </div>
	 <?php endif;  
	   
}?>