<?php 
/**
 * @author		Sashas
 * @category    Sashas
 * @package     Sashas_Callforprice
 * @copyright   Copyright (c) 2013 Sashas IT Support Inc. (http://www.sashas.org)
 * @license     http://opensource.org/licenses/GPL-3.0  GNU General Public License, version 3 (GPL-3.0)

 */

$_product=$this->getProduct();
if (empty($_product))
 	$_product= Mage::registry('current_product');

$customer_group=$this->GetGroupId();
$show_cart=0;
$model=Mage::getModel('callforprice/callforprice')->loadByProductId($_product->getId());
 
if ($model->getId() && $model->getAddtocartEnabled()==1) {
	$show_cart=1;	
}
if (!$model->getId() || !$model->getStatus()) {
	$show_cart=1;
}
if (in_array($customer_group, explode(',',$model->getCustomerGroups()))) {
	$show_cart=1;
}
if ($show_cart){	 
  $buttonTitle = $this->__('Add to Cart');  
	  if($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <div class="pull-left">
            <?php if(!$_product->isGrouped()): ?>
                <div class="pull-left">
                    <label for="qty"><?php echo $this->__('Quantity') ?></label>
                    <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
                </div>
                <div class="custom pull-left">
                    <button type="button" class="increase items-count" onclick="var result = document.getElementById('qty'); var qty = result.value; if( !isNaN( qty )) result.value++;return false;"><i class="fa fa-angle-up"></i></button>
                    <button type="button" class="reduced items-count" onclick="var result = document.getElementById('qty'); var qty = result.value; if( !isNaN( qty ) && qty > 0 ) result.value--;return false;"><i class="fa fa-angle-down"></i></button>
                </div>
            <?php endif; ?>
        </div>
        <div class="pull-right">
        <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $buttonTitle ?></span></span></button>
        <?php echo $this->getChildHtml('', true, true) ?>
        </div>
    </div>
	 <?php endif;  
	   
}

 