<?php 
/**
 * @author		Sashas
 * @category    Sashas
 * @package     Sashas_Callforprice
 * @copyright   Copyright (c) 2014 Sashas IT Support Inc. (http://www.sashas.org)
 * @license     http://opensource.org/licenses/GPL-3.0  GNU General Public License, version 3 (GPL-3.0)
 */
?>
<?php 
   $_product = $this->getProduct();
   $without_stock=$this->getWithoutStock(); 
   $stock_only=$this->getStockOnly();
?>

<?php  if ($_product->isAvailable() && !$without_stock): ?>
    <p class="availability in-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('In stock') ?></span></p>
<?php elseif (!$without_stock) : ?>
    <p class="availability out-of-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('Out of stock') ?></span></p>
<?php  endif; ?>
<?php   echo $this->getChildHtml('product_type_data_extra') ?>

<?php 
if (!$stock_only):
	$model=Mage::getModel('callforprice/callforprice')->loadByProductId($_product->getId());
	$customer_group=$this->GetGroupId();
	if ($model->getId() && $model->getStatus()==1 && !in_array($customer_group, explode(',',$model->getCustomerGroups())) ):
?>
<div class="price-box"><span id="product-price" class="regular-price"><span class="price"><div class="call-for-price"><?php echo $this->__($model->getValue());?></div></span></span></div>
<?php   else:   
		echo Mage_Catalog_Block_Product::getPriceHtml($_product);
?>
<?php endif;?>	 
<?php endif;?>	 